Add locale on users creation
georgestam/SF-UAE pull request #12
Opened 2017-05-07 16:22 UTC by georgestam

@vemv I have added a `locale` string variable to `users`. In this way, the platform will know whether the user speaks Arabic or English, when the user is created.

2017-05-07 16:42 UTC, vemv requested changes

2017-05-07 16:42 UTC, vemv commented on app/models/user.rb
> +  validates :locale, inclusion: { in: LANGUAGES, allow_nil: false }
change this for:

`inclusion: LANGUAGES`

That forbids nil too

2017-05-07 16:42 UTC, vemv commented on config/initializers/devise.rb
> +  config.password_length = Rails.env.development? ? 1..72 : 8..255
production passwords should have 10 at least, 8 is too few

2017-05-07 16:42 UTC, vemv commented on spec/features/user_registration_spec.rb
> +  it 'works' do
try to keep `'works'` at a minimum.

Instead:

`it 'results in a User being created'`

2017-05-07 16:42 UTC, vemv commented on app/controllers/registrations_controller.rb
> +    params.require(:user).permit(:name, :email, :password, :password_confirmation).merge(:locale => I18n.locale)
as part of this PR, change `before_action :set_locale` with `around_action :set_locale`, and the following implementation:

```ruby
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    yield
    I18n.locale = I18n.default_locale
  end
```

The point is to not let Arabic users change the global locale for all users.

2017-05-07 18:05 UTC, georgestam commented on app/controllers/registrations_controller.rb
> +    params.require(:user).permit(:name, :email, :password, :password_confirmation).merge(:locale => I18n.locale)
> The point is to not let Arabic users change the global locale for all users.

What do you mean by 'all users'? how can a user change the 'global locale' for all the users? 

I think that understand how `around_action`works but I have difficulties to see its practical applicability in this (or other) example...

2017-05-08 11:37 UTC, georgestam commented
@vemv I have implemented the changes.

2017-05-08 11:41 UTC, georgestam reviewed
@vemv I have added a couple of comments

2017-05-08 11:41 UTC, georgestam commented on app/controllers/application_controller.rb
> +    if language = request.env['HTTP_ACCEPT_LANGUAGE']
Rubocop complains about this line, how can I refactor this?
```app/controllers/application_controller.rb:50:17: W: Assignment in condition - you probably meant to use ==.
    if language = request.env['HTTP_ACCEPT_LANGUAGE']

2017-05-08 11:41 UTC, georgestam commented on spec/features/locales_spec.rb
>      page_ok
I spent a lot of time trying to use the `lang` attribute from the `html` tag without success. So, I implemented this solution instead.

2017-05-08 11:51 UTC, vemv requested changes

2017-05-08 11:51 UTC, vemv commented on spec/features/locales_spec.rb
> +    expect{ find("#change-to-arabic").click }.to change{ page.current_path }.from("/en").to("/ar")
Good! but you could additionally add:

`.and change{ find('html')[:lang] }.from('en').to('ar')`

You can find and example of rspec `.and` in kuina.

2017-05-08 11:51 UTC, vemv commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
not good, much less without a comment

2017-05-08 11:51 UTC, vemv commented on app/controllers/application_controller.rb
> +  def extract_locale_from_accept_language_header
* Only return `locale` if `locale.in?(User::LANGUAGES)`

* Cover this method with a spec. Does it correctly derive `en` from `en`, `en-US`, etc?

* For easier testability, you can extract this method to a new dedicated class like `app/lib/http_accept_lang_parser.rb`. That class would accept a string as an argument, passed from ApplicationController:

```
def extract_locale_from_accept_language_header
  HttpAcceptLangParser.parse(request.env['HTTP_ACCEPT_LANGUAGE'])
end
```

That way in your unit tests you only test HttpAcceptLangParser and don't have to worry about instantiating ApplicationController or manipulating `request`

2017-05-08 11:51 UTC, vemv commented on app/models/user.rb
> +  validates :locale, inclusion: { in: LANGUAGES }
`inclusion: LANGUAGES`, just like that

2017-05-08 11:53 UTC, vemv commented on app/controllers/application_controller.rb
> +    if language = request.env['HTTP_ACCEPT_LANGUAGE']
```
language = request.env['HTTP_ACCEPT_LANGUAGE'].presence
if language
```

2017-05-08 11:53 UTC, vemv commented on spec/features/locales_spec.rb
>      page_ok
Doesn't `find('html')[:lang]` work?

2017-05-08 12:08 UTC, georgestam commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
I am not creating users to login, I just want to add them to the database (but I need one admin). Before I had hidden fields with the password in the `simple_for,` I think that this approach looks better.

2017-05-08 13:10 UTC, georgestam commented
@vemv I have implemented the changes.

2017-05-08 15:12 UTC, vemv requested changes
Almost there...

2017-05-08 15:12 UTC, vemv commented on app/controllers/application_controller.rb
> +      locale.in?(User::LANGUAGES) ? locale : nil
move this conditional logic to HttpAcceptLangParser, so all logic (knowledge) is centralized in a single place

2017-05-08 15:12 UTC, vemv commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
Creating a signup page just for admin is a) overkill, and b) a security risk. Create them in seeds or `rails c`.

You can keep an `edit` page so admins can update their password, but that should be it

2017-05-08 15:12 UTC, vemv commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
One lesson that one can extract is that workaround code is rarely necessary. Attack causes not symptoms!

2017-05-08 15:12 UTC, vemv commented on spec/features/accept_language_spec.rb
> +  it "parses Accept-Language header into locale string en" do
This is a good start, but remember the golden rule: tests must be **correct** and **complete**.

This is clearly not complete, it only covers a single string. Does it work for `ar` too?

Can you gather a few extra real examples and add them here?

2017-05-08 15:12 UTC, vemv commented on spec/features/locales_spec.rb
> +    }.from("en").to("ar")
Awesome!

2017-05-08 15:12 UTC, vemv commented on app/controllers/application_controller.rb
> +      locale.in?(User::LANGUAGES) ? locale : nil
Additionally: beware of comparing strings with symbols. What if tomorrow your code looked like this?

`LANGUAGES = %i[ar en].freeze`

(array of symbols)

Such a change is plausible, given that `I18n.locale` always returns a symbol, and as you gain experience you'll use symbols more frequently.

So, a safe comparison would be:

`locale.to_s.in?(User::LANGUAGES.map(&:to_s))`

2017-05-08 21:53 UTC, georgestam reviewed
@vemv I have implemented the changes.

2017-05-08 21:53 UTC, georgestam commented on app/controllers/application_controller.rb
> +      locale.in?(User::LANGUAGES.map(&:to_sym)) ? locale : nil
I noticed that was better to convert it to symbol rather to string, as the `I18n.locale` is returning a symbol (somehow both, symbol and string, seem to work).

2017-05-08 21:53 UTC, georgestam commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
I did not mean to have a login feature for an admin, what I meant is that I would like to use devise and the users table for both admins and users. Now users do not login, but it is likelty the they will be soon, so I wanted to keep the feature as it is with users/devise.

2017-05-08 23:31 UTC, vemv requested changes

2017-05-08 23:31 UTC, vemv commented on app/controllers/application_controller.rb
> +      locale.in?(User::LANGUAGES.map(&:to_sym)) ? locale : nil
The bad part is that `nil.to_sym` raises an error.

It's good do define and return things as symbols. Keep that. But when comparing, always convert both parts to string.

This rule only applies to strings/symbols - not integers or any other type

2017-05-08 23:31 UTC, vemv commented on app/controllers/application_controller.rb
> +      locale.in?(User::LANGUAGES.map(&:to_sym)) ? locale : nil
> locale.in?(User::LANGUAGES.map(&:to_sym)) ? locale : nil

remember to move this logic to HttpAcceptLangParser.

2017-05-08 23:31 UTC, vemv commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
Sounds good, just think of a way of eliminating the need for `SecureRandom.hex(10)`.

2017-05-09 08:18 UTC, georgestam reviewed
@vemv done!

2017-05-09 08:18 UTC, georgestam commented on app/controllers/registrations_controller.rb
> +    password = SecureRandom.hex(10)
Yes, it was an easier way! I added this to `user.rb`: 
```
def password_required?
    super if self.admin
 end

2017-05-09 09:05 UTC, vemv commented on app/models/user.rb
> +    super if self.admin
Looks good, but why does the method return `nil` for non-admins?

Couldn't you return `true` for everyone instead?

2017-05-09 09:20 UTC, georgestam commented
@vemv I have implemented your change. Is there any reason why do you prefer to show `nil` instead of `false`?

2017-05-09 09:29 UTC, vemv commented
You misunderstood my question.

This was the important part:

> Couldn't you return true for everyone instead?

2017-05-09 09:44 UTC, merged