conf staging implemented
georgestam/SF-UAE pull request #7
Opened 2017-04-29 20:14 UTC by georgestam

@vemv, PR from issue #6 - Just `staging` environment added for a new heroku app. 

(Codeship built will not pass as there is the another PR opened that fixes robucop)

2017-04-29 20:20 UTC, vemv requested changes

2017-04-29 20:20 UTC, vemv commented on config/initializers/global_functions.rb
> +  Rails.env.production?
wtf? that's one deceiving name if I ever saw one :)

production != staging, they're different environments

2017-04-29 20:20 UTC, vemv commented on config/environments/staging.rb
> +Rails.application.configure do
Regading configuration, it is key that staging remains as close to production as possible, now and in the future.

Therefore copy the production_or_staging.rb file/pattern from kuina.

2017-04-29 20:20 UTC, vemv commented on config/initializers/global_functions.rb
> +def staging_or_production?
call it `production_or_staging? - you should care/think about the most important thing first.

2017-04-30 20:08 UTC, georgestam commented
@vemv I have implemented the changes (codeship still fails due to rubocop fixed in another PR)

2017-04-30 20:11 UTC, vemv commented on config/initializers/global_functions.rb
>  def development_or_production?
this is bit of a weird function to have, to you need it?

2017-04-30 20:12 UTC, vemv approved these changes
Approved, just possibly delete development_or_production (because it implies staging would return false)

2017-04-30 20:13 UTC, georgestam commented on config/initializers/global_functions.rb
>  def development_or_production?
I would like to test MailChimp subscription and Postmark on both, but not on development and testing. is this a normal procedure?

2017-04-30 20:33 UTC, merged