Rspec and Capybara/Selenium Setup
georgestam/SF-UAE pull request #9
Opened 2017-05-01 19:57 UTC by georgestam

PR from issue #8 - Rspec and Capybara/Selenium Setup.

I have also written a couple of tests for the landing page and locale selector.

2017-05-01 21:08 UTC, georgestam reviewed
@vemv, could you please review this PR? 

I have also added a few queries in code.

2017-05-01 21:08 UTC, georgestam commented on spec/spec_helper.rb
> +    ex.run_with_retry retry: (ci? ? 3 : 2), retry_wait: 3
`ci?` to be modified as per above.

2017-05-01 21:08 UTC, georgestam commented on config/initializers/global_functions.rb
> +  # [ENV['CODESHIP'], ENV['CI']].any? &:present?
I assume that `ci` stands for Travis IC, which is not relevant here. I would like to remove this method, but I have 2 questions:
1. Not sure what is purpose of  line `80` from `spec_helper.rb` - ```ex.run_with_retry retry: (ci? ? 3 : 2), retry_wait: 3```. is it related with my `onerror`question above?
2. Where the variable `[ENV['CODESHIP']` is defined? If it is a key, I do not need any keys in my app to run the basic version of codeship. How can I tell to my app that I am in the codeship enviroment? Should not be enough to use `test?`(line 7 from `spec_helper.rb` uses `unless ENV['CODESHIP'])`

2017-05-01 21:08 UTC, georgestam commented on app/views/layouts/application.html.haml
> +        }
Could you please remind me why this block of code is required? `onerror`seems an event to be triggered if an error occurs while loading an external file, but what are the `(a, b, c)` arguments?

2017-05-01 21:23 UTC, vemv requested changes

2017-05-01 21:23 UTC, vemv commented on config/initializers/global_functions.rb
> +  # [ENV['CODESHIP'], ENV['CI']].any? &:present?
CI meants Continuous Integration. Not travis-specific

1. It configurates the `rspec-retry` gem
2. Codeship sets an env var named `CODESHIP`. What `ci?` does is to determine whether code is being run by a CI provider. Either `ENV['CODESHIP']` or `ENV['CI']` would prove that

2017-05-01 21:23 UTC, vemv commented on spec/spec_helper.rb
> +    ex.run_with_retry retry: (ci? ? 3 : 2), retry_wait: 3
No modification needed

2017-05-01 21:23 UTC, vemv commented on app/views/layouts/application.html.haml
> +        }
This backs the implementation of `assert_js_ok`. `assert_js_ok` must be run after every JS test. See kuina spec_helper and also `def assert_js_ok`

2017-05-01 21:23 UTC, vemv commented on Gemfile
> +gem 'rails', '5.0.1'
Generally, don't update `rails` lightly. Dedicate a commit or even a branch to it. When doing so, review why are you doing it, and also make sure to follow the rails upgrade guides (http://guides.rubyonrails.org/upgrading_ruby_on_rails.html)

This time is no big deal, next one remember it

2017-05-01 21:23 UTC, vemv commented on Gemfile
> +  gem 'rubocop', '~> 0.48.1'
* Keep Gemfile sorted alphabetically, leveraging atom `sort-lines` plugin
* Don't introduce random blank lines

2017-05-01 21:23 UTC, vemv commented on spec/controllers/pages_spec.rb
> +      it 'diplays the landing page' do
* This test doesn't really assert that it `diplays the landing page`. It merely asserts that the page `loads correctly`. Update the string so the message is truthful

* Try to no commit typos (`diplays`). Self-code-review habit might help

2017-05-01 21:23 UTC, vemv commented on spec/features/locales_spec.rb
> +      find("#change-to-arabic").click
Tests that assert that a page loads are too weak when you introduce interactions such as `find("#change-to-arabic").click`.

Instead (or additionally), assert that clicking the button does something.

Probably: `expect{ find("#change-to-arabic").click }.to change{ current_url }.from(x).to(y)`

2017-05-02 11:24 UTC, georgestam commented
@vemv I have implemented your requested changes.

2017-05-02 11:40 UTC, vemv requested changes

2017-05-02 11:40 UTC, vemv commented on app/views/shared/_navbar_top.html.haml
> +              = link_to (t '.english'), url_for( :locale => 'en'), id:"change-to-english"
For the next time, space between `:` and `"`. Now leave it, let's move quick

2017-05-02 11:40 UTC, vemv commented on spec/controllers/pages_spec.rb
> +    context 'when it is loaded' do
`context` must never do nothing.

In this case it's doing nothing - it's a wrapper block which doesn't provide anything.

`context` blocks must always be accompanied of stuff like:

* `let` / `def`
* `before` / `after`

In this case, you can move `get 'index'` to a `before` block belonging to the `context` block. That way the `context` would do something - there would be a relationship between the text `'when it is loaded'` and an actual piece of code.

2017-05-02 11:40 UTC, vemv commented on spec/features/locales_spec.rb
> +describe 'locale' do
You're not describing `locale`-  you're describing `locale switching` or something like that.

Pay attention to these

2017-05-02 11:40 UTC, vemv commented on spec/features/locales_spec.rb
> +    it 'loads page' do
`'when arabic is selected it loads page'` does not read like a well-constructed, informative piece of English that reflects a feature of the app.

2017-05-02 11:40 UTC, vemv commented on spec/features/locales_spec.rb
> +    it 'changes language' do
Same comment as above for `when arabic is selected it changes language`

2017-05-02 12:10 UTC, georgestam commented
@vemv I have implemented the changes.

2017-05-02 12:22 UTC, vemv requested changes

2017-05-02 12:22 UTC, vemv commented on spec/features/locales_spec.rb
> +  context 'when arabic is selected' do
You say `when arabic is selected` but the code says `visit root_path(:en)`. You shouldn't lie! ;p

* move `visit root_path(:en)` at `describe` level
* Delete this test altogether:

```
     it 'loads page' do
       find("#change-to-arabic").click
       page_ok
     end
```
* Add a `page_ok` at the end of the remaining `it`
* Review the result and make sure it makes sense / adheres to guidelines

2017-05-02 12:34 UTC, georgestam commented on spec/features/locales_spec.rb
> +  context 'when arabic is selected' do
Then, I will have to remove the `context` of this test as you mentioned before that it should always have some 'stuff' such as 'let / def' or 'before / after'. Correct?

2017-05-02 12:46 UTC, vemv commented
Yes, probably

On Tue, May 2, 2017 at 2:34 PM, Jordi Fernandez <notifications@github.com>
wrote:

> *@georgestam* commented on this pull request.
> ------------------------------
>
> In spec/features/locales_spec.rb
> <https://github.com/georgestam/SF-UAE/pull/9#discussion_r114307319>:
>
> > @@ -0,0 +1,20 @@
> +describe 'locale switching' do
> +
> +  context 'when arabic is selected' do
>
> Then, I will have to remove the context of this test as you mentioned
> before that it should always have some 'stuff' such as 'let / def' or
> 'before / after'. Correct?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/georgestam/SF-UAE/pull/9#discussion_r114307319>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABG-8o0N6iBRZvsJVni4R6oVztuUU1qaks5r1yLigaJpZM4NNX3S>
> .
>

2017-05-02 12:55 UTC, georgestam commented
@vemv Done.

2017-05-02 12:59 UTC, vemv approved these changes
Excellent, thank you!

I guess this was bit of a tiresome process, but better to   set a good level since the beginning

These will be less frequent, especially if you internalize these lessons.

2017-05-02 13:16 UTC, georgestam commented
Thanks to your Victor!  💯

2017-05-02 13:16 UTC, merged